if True:
    class 前川:
        def 付き纏い_春代():
            ...
        def 付き纏い_ノア():
            ...
        def 告発メール送信():
            print("[指定時刻] 私は殺されました")
        ...
    class 青瀬:
        ...
    class ニナ:
        ...
    class 丸尾:
        ...
    class 保科:
        ...
    class 飯野:
        def 前社員に指摘():
            ...
        def 青瀬殺害計画():
            ...
        ...
    class 大森:
        def 前川殺害():
            ...
        def 失踪メール送信():
            print("失踪します 前川")
        def ノア殺害():
            ...
        ...
    class 春代:
        ...
    class ノア:
        ...
    class 所長:
        """事業所長"""
        ...
    class 大林部長:
        ...
    class 佐伯:
        ...
    class 事業所員:
        ...
    class 事業所外社員:
        ...
