from __future__ import annotations
if True:
    class x: ...
    class 予測結果: ...
    class 実測結果: ...

    def 予測(前提):
        return 予測結果()
    def 実測():
        return 実測結果()
    def 評価(予測結果_: 予測結果, 実測結果_: 実測結果):
        x.比較(予測結果_, 実測結果_)
        ...
    def 評価待機(予測結果_: 予測結果):
        if 予測結果_.トリガー条件:
            実測結果_ = 実測()
            評価(予測結果_, 実測結果_)
        ...
    ...
